name: package-linters

on:
  pull_request:
    branches: ["main", "develop"]


jobs:

  code_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8==6.0.* pylint==2.17.* black==23.7.0 isort==5.12.* pytest
      - name: Run linters
        run: |
          isort --check src unittests
          black --check src unittests
          pip install .
          flake8 --tee --format=pylint src unittests
          pylint --rcfile=pylintrc src unittests
